#!/bin/bash
# Deploy ProStudio to EC2

echo "📦 ProStudio EC2 Deployment Instructions"
echo "======================================="
echo ""
echo "1. SSH into your EC2 instance:"
echo "   ssh -i prostudio-key.pem ubuntu@54.172.247.70"
echo ""
echo "2. Once connected, run these commands:"
echo ""
echo "   # Clone the ProStudio repository"
echo "   git clone https://github.com/yourusername/prostudio.git"
echo "   cd prostudio"
echo ""
echo "   # Copy the deployment files"
echo "   cp deploy/zero-cost/docker-compose.yml ."
echo "   cp deploy/zero-cost/nginx.conf deploy/zero-cost/"
echo ""
echo "   # Start ProStudio"
echo "   docker-compose up -d"
echo ""
echo "3. Access ProStudio at:"
echo "   http://54.172.247.70/health"
echo ""
echo "Note: ProStudio uses Redis (not PostgreSQL) and Flask (not Next.js)"